#include <complex.h>
#include "keycodes.h"
#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif
#include "user_song_list.h"

enum planck_keycodes { BACKLIT, EXT_PLV };
/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

      /* Default Base Layer 0 to be _BASE */
    [0] = LAYOUT_planck_2x2u(
          QK_GESC,  KC_Q,         KC_W,     KC_E,     KC_R,            KC_T,  KC_Y,    KC_U,     KC_I,     KC_O,          KC_P,     KC_BSPC,
          KC_LCTL,  KC_A,         KC_S,     KC_D,     KC_F,            KC_G,  KC_H,    KC_J,     KC_K,     KC_L,          KC_SCLN,  KC_QUOT,
          KC_LSFT,   KC_Z,         KC_X,     KC_C,     KC_V,            KC_B,  KC_N,    KC_M,     KC_COMM,  KC_DOT,        KC_SLSH, RSFT_T(KC_ENT) ,
          MO(1),    LCA(KC_DEL),  KC_LGUI,  KC_LALT,  KC_TAB,                          KC_SPC,  KC_LEFT,  KC_DOWN,  KC_UP,    LT(2,KC_RGHT)
    ),
      /* MO1 Nav, Numbers */
    [1] = LAYOUT_planck_2x2u(
          KC_TRNS,  KC_1,         KC_2,     KC_3,     KC_4,     KC_5,     KC_6,     KC_7,     KC_8,     KC_9,     KC_0,     KC_DEL,
          KC_TRNS,  KC_TRNS,      KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_LEFT,  KC_DOWN,  KC_UP,    KC_RGHT,  KC_TRNS,  KC_TRNS,
          KC_TRNS,  KC_TRNS,      KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_HOME,  KC_PGDN,  KC_PGUP,  KC_END,   KC_BSLS,  KC_TRNS,
          MO(1),  LCA(KC_DEL),  KC_LGUI,  KC_LALT,  KC_LSFT,                              KC_ENT,   KC_TRNS,  KC_TRNS,  KC_TRNS,  MO(2)
    ),
      /* MO2 Symbols, Numbers */
    [2] = LAYOUT_planck_2x2u(
          KC_TRNS,  KC_EXLM,  KC_AT,    KC_HASH,  KC_DLR,   KC_PERC,  KC_CIRC,  KC_AMPR,  KC_ASTR,  KC_LPRN,  KC_RPRN,  KC_TRNS,
          KC_TRNS,  KC_LCBR,  KC_RCBR,  KC_UNDS,  KC_PIPE,  KC_LT,    KC_GT,    KC_SLSH,  KC_MINS,  KC_LBRC,  KC_RBRC,  KC_TRNS,
          KC_TRNS,  KC_TRNS,  KC_DOT,   KC_PPLS,  KC_LPRN,  KC_SCLN,  KC_COLN,  KC_RPRN,  KC_PMNS,  KC_PEQL,  KC_TRNS,  KC_TRNS,
          MO(1),    KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_LSFT,  KC_ENT,   KC_TRNS,  KC_TRNS,  KC_TRNS,  MO(2)
    ),
    [3] = LAYOUT_planck_2x2u(
      /* CS2 */
          KC_ESC,  KC_NO,  QK_GESC,  KC_1,  KC_2,    KC_3,  KC_4,   KC_NO,  KC_NO,  KC_NO,  KC_NO,  TO(0),
          KC_NO,   KC_G,   KC_LCTL,  KC_Q,  KC_W,    KC_E,  KC_R,   KC_T,   KC_Y,   KC_U,   KC_I,   KC_O,
          KC_NO,   KC_B,   KC_LSFT,  KC_A,  KC_S,    KC_D,  KC_F,   KC_G,   KC_H,   KC_J,   KC_K,   KC_NO,
          MO(1),   KC_NO,  KC_Z,     KC_X,  KC_SPC,  KC_C,  KC_NO,  KC_NO,  KC_NO,  MO(2)
    ),
      /* CyberPunk 2077 */
    [4] = LAYOUT_planck_2x2u(
          KC_ESC,  KC_NO,  KC_1,     KC_2,  KC_3,    KC_4,  KC_5,   KC_6,   KC_NO,  KC_NO,  KC_NO,    TO(0),
          KC_NO,   KC_G,   KC_LCTL,  KC_Q,  KC_W,    KC_E,  KC_R,   KC_T,   KC_NO,  KC_NO,  KC_NO,    KC_NO,
          KC_NO,   KC_B,   KC_LSFT,  KC_A,  KC_S,    KC_D,  KC_R,   KC_NO,  KC_NO,  KC_NO,  KC_NO,    KC_NO,
          MO(1),   KC_NO,  KC_Z,     KC_X,  KC_SPC,                         KC_C,   KC_NO,  KC_NO,  KC_NO,MO(2)
     ),
      /* Settings */
    [5] = LAYOUT_planck_2x2u(
          _______, QK_BOOT, DB_TOGG, UG_TOGG, UG_NEXT, UG_HUEU, UG_HUED, UG_SATU, UG_SATD, UG_SPDU, UG_SPDD, KC_DEL ,
          _______, EE_CLR,  MU_NEXT, AU_ON,   AU_OFF,  AG_NORM, AG_SWAP, TO(0),  TO(3), TO(4),  KC_NO,  _______,
          _______, AU_PREV, AU_NEXT, MU_ON,   MU_OFF,  MI_ON,   MI_OFF,  _______, _______, _______, _______, _______,
          MO(1),   KC_NO,  KC_NO,     KC_NO,  KC_NO,                     KC_NO,   KC_NO,  KC_NO,  KC_NO,MO(2)
     )
};


#ifdef AUDIO_ENABLE
float cp2077_v[][2]    = SONG(CP2077_V);
#endif


const custom_shift_key_t custom_shift_keys[] = {
  {KC_LPRN ,  KC_RPRN}, // Shift ( is )
  {KC_LCBR ,  KC_RCBR}, // Shift { is }
  {KC_LBRC ,  KC_RBRC}, // Shift [ is ]
};

layer_state_t layer_state_set_user(layer_state_t state) {
    return update_tri_layer_state(state, 1, 2, 5);

    static bool is_adjust_layer_on = false;
  if (layer_state_cmp(state, 4) != is_adjust_layer_on) {
    is_adjust_layer_on = layer_state_cmp(state, 4);
    if (is_adjust_layer_on) {
      PLAY_SONG(cp2077_v); // Replace my_song with your desired song
    } else {
      stop_all_notes();
    }
  }
  return state;
}

/*layer_state_t layer_state_set_user(layer_state_t state) {
*    static bool is_this_layer_on = false;
*    if (layer_state_cmp(state, 0) != is_this_layer_on) { // Check if layer 3 is activated/deactivated
*        is_this_layer_on = layer_state_cmp(state, 0);
*        if (is_this_layer_on) {
*            PLAY_SONG(QWERTY_SOUND); // Play the song when layer 3 is activated
*        } else {
*            stop_all_notes(); // Stop the sound when layer 3 is deactivated
*        }
*    }
*    return state;
*}
 */
